### ISSUE TITLE
Crash on startup with Optifine

### ISSUE THREAD

**Issue by Archilyte** [EDToaster/LittleContraptions#5]
This mod crashes on startup with optifine installed. All required dependencies are present. Removing with this mod or optifine seems to solve this issue. More details here: https://github.com/sp614x/optifine/issues/6753

**Comment by EDToaster** [comment]
Adding logs here for convenience: https://gist.github.com/Archilyte/50a69e5aefd0db9dc62282e09476e02c

**Comment by EDToaster** [comment]
Optifine version: 1.18.2 HD_U_H7

**Comment by EDToaster** [comment]
I'm unable to reproduce this bug with Flywheel, Create, LL, LC, and Optifine installed:

Versions:
* LC: 1.18.2.0-beta.3
* LL: 1.2.1
* Flywheel: 0.6.2
* Create: 0.4.1
* Optifine: 1.18.2_HD_U_H7
* Forge: 40.0.52
Can you provide more details on specific mod/forge versions and steps to reproduce the crash? Are you using a dedicated server?

**Comment by Archilyte** [comment]
all of those mod versions are what i am using, and the crash either seems to be at startup or when loading/generating a world...

EDIT: its singleplayer

**Comment by Archilyte** [comment]
I can't seem to be able to recreate this issue with everything set to the latest version as of this comment, so I will be closing this for now.
